

DRI_Record_Type_Dict = \
{
    0: 'DRI_MT_PHDB',
    1: 'DRI_MT_WAVE',
    2: 'DRI_MT_ARMS',
    3: 'DRI_MT_B2B_CTRL',
    4: 'DRI_MT_ALARM',
    5: 'DRI_MT_NETWORK',
    6: 'DRI_MT_PRINT',
    7: 'DRI_MT_SERV',
    8: 'DRI_MT_FO',
    9: 'DRI_MT_ACK',
    10: 'DRI_MT_EVENT',
    11: 'DRI_MT_MEM',
    12: 'DRI_MT_MODES',
    13: 'DRI_MT_IND',
    14: 'DRI_MT_TEST',
    15: 'DRI_MT_INPH',
    16: 'DRI_MT_ADU_INTF_PHDB',
    17: 'DRI_MT_DEBUG',
    18: 'DRI_MT_SNAPSHOT',
    19: 'DRI_MT_CASE',
}

DRI_Subrecord_WF_Type_Dict = \
{
    0: 'DRI_WF_CMD',
    1: 'DRI_WF_ECG1',
    2: 'DRI_WF_ECG2',
    3: 'DRI_WF_ECG3',
    4: 'DRI_WF_INVP1',
    5: 'DRI_WF_INVP2',
    6: 'DRI_WF_INVP4',
    7: 'DRI_WF_INVP2',
    8: 'DRI_WF_PLETH',
    9: 'DRI_WF_CO2',
    10: 'DRI_WF_O2',
    11: 'DRI_WF_N2O',
    12: 'DRI_WF_AA',
    13: 'DRI_WF_AWP',
    14: 'DRI_WF_FLOW',
    15: 'DRI_WF_RESP',
    16: 'DRI_WF_INVP5',
    17: 'DRI_WF_INVP6',
    18: 'DRI_WF_EEG1',
    19: 'DRI_WF_EEG2',
    20: 'DRI_WF_EEG3',
    21: 'DRI_WF_EEG4',
    22: 'DRI_WF_ECG12',
    23: 'DRI_WF_VOL',
    24: 'DRI_WF_TONO_PRESS',
    25: 'DRI_WF_VENT_AWP',
    26: 'DRI_WF_VENT_FLOW',
    27: 'DRI_WF_VENT_VOL',
    28: 'DRI_WF_NIBP',
    29: 'DRI_WF_SPI_LOOP_STATUS',
}
